# Generated by Django 4.0.7 on 2023-07-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_auth',
            field=models.BooleanField(default=False),
        ),
    ]
