# Generated by Django 4.0.7 on 2023-07-07 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('copies', '0001_initial'),
        ('loans', '0007_loan_delay_alter_loan_copy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='delay',
        ),
        migrations.AlterField(
            model_name='loan',
            name='copy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='copies.copy'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='expected_return',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to=settings.AUTH_USER_MODEL),
        ),
    ]
