# Generated by Django 4.0.7 on 2023-07-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_remove_loan_delay_alter_loan_copy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='return_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
