# Generated by Django 4.0.7 on 2023-07-12 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_alter_loan_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='returnDate',
            field=models.DateField(default=datetime.date(2023, 7, 19)),
        ),
    ]
